# Project information
site_name: OpenBlock
site_url: https://wiki.openblock.cc/en/
site_author: OpenBlock Team
site_description: >-
  OpenBlock English Wiki

# Repository
repo_name: openblockcc/wiki
repo_url: https://github.com/openblockcc/wiki/tree/en

# Configuration
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
  icon:
    logo: material/library
  favicon: assets/favicon.png
  logo: 'assets/logo.svg'

# Copyright
copyright: Copyright &copy; 2020 - 2021 openblock.cc

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openblockcc

# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Page tree
nav:
  - Home: 
    - Home: index.md
    - Download software: download-software.md
    - Visit online version: visit-online-version.md
    - Copyright Notice:
      - License: license.md
      - Trademark: trademark.md
  - General user:
    - Quick start: normal-user/quick-start.md
    - Interface introduction: normal-user/interface-introduction.md
  - Developer:
    - Develop extensions:
      - Quick start: developer/develop-extensions/quick-start.md
      - Reference: developer/develop-extensions/reference.md
    - Customization:
      - Introduction: developer/customization/introduction.md
      - Reference: developer/customization/reference.md
    - Develop from source:
      - Quick start: developer/develop-from-source/quick-start.md
      - Framework introduction: developer/develop-from-source/framework-introduction.md
      - Add a new board: developer/develop-from-source/add-a-new-board.md
      - Pack desktop software: developer/develop-from-source/pack-desktop-software.md
      - Localization: developer/develop-from-source/localization.md
  - Business service:
    - Introduction: business-service/introduction.md
  - Changelog:
    - Desktop changelog: desktop-changelog.md
    - Link changelog: link-changelog.md